### ISSUE TITLE
I got error message "Request failed with status code 401"

### ISSUE THREAD

**Issue by openmind-gnerlich** [multimeric/AmplifyCountDirective#13] opened 2022-09-19 14:00 UTC
How can I controll iam auth for @count? I want to get count over IAM. It is not working.

My schema:
```type SignSuggestion
@count
@model
@auth(rules: [
    {allow: public, provider: iam},
    {allow: groups, groups: ["admin"], operations: [create,delete,read,update]}
])
{
    id: ID!
    caption: String
    video: Video! @hasOne
    userId: Ticket! @hasOne
    LikeSuggestions: [LikeSuggestion] @hasMany(indexName: "bySignSuggestion", fields: ["id"])
    approvalStatus: ApprovalStatusEnum!
    reasonForRejection: String,
    updatedAt: AWSDateTime!
}```

**Comment by multimeric** [comment] 2022-09-19 14:27
Yes, this is currently a missing feature, I believe this is a duplicate of #4. I don't actually have time to resolve this at the moment, but I would happily review a PR. You could refer to the amplify source code for the list resolver and work out how to apply it to the count resolver implemented here.

**Closed as completed by multimeric** 2022-09-19 14:27 UTC
